#!/usr/bin/zsh

# Built-in commands
alias ls="exa --long --no-time --no-user --no-permissions $@"
alias cat="bat $@"
alias less="bat $@"

# Extra aliases
alias nano="micro $@"
alias reload="clear && source $HOME/.zshrc"
alias pbar="bash $HOME/.config/polybar/launch.sh"
alias novnc="cd && ./launch_novnc.sh"

# Python aliases
alias pip="$(which python3) -m pip $@"
