# The LOCAL URL of your server (hostnames supported)
# If you want discord to use the art url your client sends, set this AND url_public to ""
url = ""

# (optional) Use a public imgproxy server? (needed most of the time)
# Obviously, you can self host your own imgproxy server as desired.
imageproxy_enabled = true
imageproxy_url = "https://images.iipython.dev"

# (optional) The public URL of your server (for port-forwarded album art, passed to imgproxy)
# Leave this BLANK if you don't want to edit the url your client sends
url_public = ""

# (optional) Time between MPRIS updates (defaults to 1 second)
# Recommended to be as fast as possible for your hardware without causing
# a major performance impact.
update_time = 0.1

# (optional) The name your client uses to identify itself over the MPRIS dbus API
# You can usually find this using a dbus client such as qdbus, however milage may vary
# Feel free to submit a PR if you get it working with a custom client
client_name = "Feishin"
