
[colors.bright]
black = "#5F6368"
blue = "#4285F4"
cyan = "#24C1E0"
green = "#34A853"
magenta = "#A142F4"
red = "#EA4335"
white = "#FFFFFF"
yellow = "#FBBC05"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.normal]
black = "#202124"
blue = "#4285F4"
cyan = "#24C1E0"
green = "#34A853"
magenta = "#A142F4"
red = "#EA4335"
white = "#E8EAED"
yellow = "#FBBC04"

[colors.primary]
background = "#202124"
foreground = "#E8EAED"

[cursor]
thickness = 0.05
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
